-- Schema target di govpay-console-api per Oracle.
--
-- Tabelle proprie di console-api (oggi nessuna: console-api riusa lo schema
-- di govpay-core). Le modifiche alle tabelle ereditate da govpay-core sono
-- nello script `upgrade-v1-to-v2.sql`.
--
-- Per applicare il bring-up completo di un DB da zero per console-api:
--   1) applicare lo schema di govpay-core (`gov_pay.sql` di govpay-381)
--   2) applicare `upgrade-v1-to-v2.sql` di questo progetto
--   3) applicare questo file (oggi no-op)
