-- Schema target di govpay-console-api per HSQLDB.
--
-- Tabelle proprie di console-api. Le modifiche alle tabelle ereditate da
-- govpay-core sono nello script `upgrade-v1-to-v2.sql`.
--
-- Per applicare il bring-up completo di un DB da zero per console-api:
--   1) applicare lo schema di govpay-core V1
--   2) applicare `upgrade-v1-to-v2.sql` di questo progetto
--   3) applicare questo file

-- Cache locale dell'anagrafica Enti Creditori sincronizzata da pagoPA
-- (scritta dal batch govpay-iban-batch, letta in sola lettura da console-api).
CREATE SEQUENCE seq_pagopa_ec_cache AS BIGINT START WITH 1 INCREMENT BY 1 ; -- (Scommentare in hsql 2.x) NO CYCLE;

CREATE TABLE pagopa_ec_cache
(
	cod_fiscale VARCHAR(16) NOT NULL,
	denominazione VARCHAR(255) NOT NULL,
	station_id VARCHAR(35),
	aux_digit VARCHAR(2) NOT NULL,
	segregation_code VARCHAR(4),
	cbill_code VARCHAR(35),
	data_ultimo_aggiornamento TIMESTAMP NOT NULL,
	cod_intermediario VARCHAR(35),
	check_stato VARCHAR(35),
	check_motivo VARCHAR(1024),
	-- fk/pk columns
	id BIGINT GENERATED BY DEFAULT AS SEQUENCE seq_pagopa_ec_cache,
	-- fk/pk keys constraints
	CONSTRAINT pk_pagopa_ec_cache PRIMARY KEY (id),
	CONSTRAINT uq_pagopa_ec_cache_cf UNIQUE (cod_fiscale)
);

CREATE TABLE pagopa_ec_cache_init_seq (id BIGINT);
INSERT INTO pagopa_ec_cache_init_seq VALUES (NEXT VALUE FOR seq_pagopa_ec_cache);

-- Cache locale degli IBAN abilitati su pagoPA per dominio, per il censimento
-- assistito dei conti di accredito (scritta dal batch govpay-iban-batch, letta
-- in sola lettura da console-api).
CREATE SEQUENCE seq_pagopa_iban_cache AS BIGINT START WITH 1 INCREMENT BY 1 ; -- (Scommentare in hsql 2.x) NO CYCLE;

CREATE TABLE pagopa_iban_cache
(
	cod_dominio VARCHAR(35) NOT NULL,
	iban VARCHAR(35) NOT NULL,
	attivo BOOLEAN NOT NULL,
	data_ultima_verifica TIMESTAMP NOT NULL,
	cod_intermediario VARCHAR(35),
	ci_name VARCHAR(255),
	status VARCHAR(255),
	validity_date TIMESTAMP,
	description VARCHAR(512),
	label VARCHAR(1024),
	check_stato VARCHAR(35),
	check_motivo VARCHAR(1024),
	-- fk/pk columns
	id BIGINT GENERATED BY DEFAULT AS SEQUENCE seq_pagopa_iban_cache,
	-- fk/pk keys constraints
	CONSTRAINT pk_pagopa_iban_cache PRIMARY KEY (id),
	CONSTRAINT uq_pagopa_iban_cache_dominio_iban UNIQUE (cod_dominio, iban)
);

CREATE TABLE pagopa_iban_cache_init_seq (id BIGINT);
INSERT INTO pagopa_iban_cache_init_seq VALUES (NEXT VALUE FOR seq_pagopa_iban_cache);
